apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cky-maf.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cky-maf.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-connection: {{ .Values.secrets.redis.connectionString | quote }}
  llm-zhipu-apikey: {{ .Values.secrets.llm.zhipuApiKey | quote }}
  qdrant-host: {{ .Values.secrets.qdrant.host | quote }}
  qdrant-port: {{ .Values.secrets.qdrant.port | quote }}
