// <auto-generated />
using System;
using CKY.MultiAgentFramework.Demos.CustomerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CKY.MultiAgentFramework.Demos.CustomerService.Data.Migrations
{
    [DbContext(typeof(CustomerServiceDbContext))]
    [Migration("20260319055114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.ChatMessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatSessionEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntitiesJson")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionEntityId")
                        .HasDatabaseName("idx_cs_chat_messages_session_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_cs_chat_messages_timestamp");

                    b.ToTable("cs_chat_messages", (string)null);
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.ChatSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_cs_chat_sessions_customer_id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("idx_cs_chat_sessions_session_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("idx_cs_chat_sessions_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_cs_chat_sessions_status");

                    b.ToTable("cs_chat_sessions", (string)null);
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("zh-CN");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("idx_cs_customers_customer_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_cs_customers_email");

                    b.ToTable("cs_customers", (string)null);
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.FaqEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_cs_faq_entries_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_cs_faq_entries_is_active");

                    b.ToTable("cs_faq_entries", (string)null);
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_cs_orders_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_cs_orders_customer_id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("idx_cs_orders_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_cs_orders_status");

                    b.ToTable("cs_orders", (string)null);
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.OrderItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderEntityId");

                    b.ToTable("cs_order_items", (string)null);
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.TicketCommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStaff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TicketEntityId");

                    b.ToTable("cs_ticket_comments", (string)null);
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.TicketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedOrderId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_cs_tickets_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_cs_tickets_customer_id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_cs_tickets_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_cs_tickets_status");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("idx_cs_tickets_ticket_id");

                    b.ToTable("cs_tickets", (string)null);
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.TrackingEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderEntityId")
                        .HasDatabaseName("idx_cs_tracking_events_order_id");

                    b.HasIndex("TrackingNumber")
                        .HasDatabaseName("idx_cs_tracking_events_tracking_number");

                    b.ToTable("cs_tracking_events", (string)null);
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.UserBehaviorRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClarificationRoundsNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntitiesJson")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TaskSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Intent")
                        .HasDatabaseName("idx_cs_user_behavior_intent");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_cs_user_behavior_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_cs_user_behavior_user_id");

                    b.ToTable("cs_user_behavior_records", (string)null);
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.ChatMessageEntity", b =>
                {
                    b.HasOne("CKY.MultiAgentFramework.Demos.CustomerService.Entities.ChatSessionEntity", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.ChatSessionEntity", b =>
                {
                    b.HasOne("CKY.MultiAgentFramework.Demos.CustomerService.Entities.CustomerEntity", "Customer")
                        .WithMany("ChatSessions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.OrderEntity", b =>
                {
                    b.HasOne("CKY.MultiAgentFramework.Demos.CustomerService.Entities.CustomerEntity", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.OrderItemEntity", b =>
                {
                    b.HasOne("CKY.MultiAgentFramework.Demos.CustomerService.Entities.OrderEntity", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.TicketCommentEntity", b =>
                {
                    b.HasOne("CKY.MultiAgentFramework.Demos.CustomerService.Entities.TicketEntity", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.TicketEntity", b =>
                {
                    b.HasOne("CKY.MultiAgentFramework.Demos.CustomerService.Entities.CustomerEntity", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.TrackingEventEntity", b =>
                {
                    b.HasOne("CKY.MultiAgentFramework.Demos.CustomerService.Entities.OrderEntity", "Order")
                        .WithMany()
                        .HasForeignKey("OrderEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.ChatSessionEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.CustomerEntity", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Orders");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.OrderEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CKY.MultiAgentFramework.Demos.CustomerService.Entities.TicketEntity", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
