import type { MafTask } from './types';

/** 模拟数据：SmartHome 睡眠模式场景 */
export const mockTasks: MafTask[] = [
  {
    id: 'task-001',
    name: '睡眠模式',
    description: '用户语音指令"开启睡眠模式"，协调灯光、空调、音乐、安防四个Agent',
    status: 'completed',
    leaderAgentId: 'sh:leader:001',
    leaderAgentName: 'SmartHomeControlService',
    userInput: '开启睡眠模式',
    createdAt: '2026-03-22T22:00:00Z',
    startedAt: '2026-03-22T22:00:00.100Z',
    completedAt: '2026-03-22T22:00:02.500Z',
    subTasks: [
      {
        id: 'sub-001',
        parentTaskId: 'task-001',
        name: '调暗灯光',
        description: '将卧室灯光调暗至30%',
        status: 'completed',
        agentId: 'sh:lighting:001',
        agentName: 'LightingAgent',
        startedAt: '2026-03-22T22:00:00.200Z',
        completedAt: '2026-03-22T22:00:00.800Z',
        result: '💡 灯光已调暗至30%',
        logs: [
          {
            id: 'log-001',
            timestamp: '2026-03-22T22:00:00.200Z',
            agentId: 'sh:lighting:001',
            agentName: 'LightingAgent',
            role: 'sub',
            action: 'SetBrightness',
            message: '设置卧室灯光亮度为30%',
            duration: 600,
            status: 'success',
          },
        ],
      },
      {
        id: 'sub-002',
        parentTaskId: 'task-001',
        name: '空调适温',
        description: '设置卧室空调温度为22°C',
        status: 'completed',
        agentId: 'sh:climate:001',
        agentName: 'ClimateAgent',
        startedAt: '2026-03-22T22:00:00.900Z',
        completedAt: '2026-03-22T22:00:01.400Z',
        result: '🌡️ 空调已调至22°C',
        logs: [
          {
            id: 'log-002',
            timestamp: '2026-03-22T22:00:00.900Z',
            agentId: 'sh:climate:001',
            agentName: 'ClimateAgent',
            role: 'sub',
            action: 'SetTemperature',
            message: '设置卧室空调为22°C制冷模式',
            duration: 500,
            status: 'success',
          },
        ],
      },
      {
        id: 'sub-003',
        parentTaskId: 'task-001',
        name: '暂停音乐',
        description: '停止播放音乐',
        status: 'completed',
        agentId: 'sh:music:001',
        agentName: 'MusicAgent',
        startedAt: '2026-03-22T22:00:01.500Z',
        completedAt: '2026-03-22T22:00:01.700Z',
        result: '🎵 音乐已暂停',
        logs: [
          {
            id: 'log-003',
            timestamp: '2026-03-22T22:00:01.500Z',
            agentId: 'sh:music:001',
            agentName: 'MusicAgent',
            role: 'sub',
            action: 'Pause',
            message: '暂停当前播放的音乐',
            duration: 200,
            status: 'success',
          },
        ],
      },
      {
        id: 'sub-004',
        parentTaskId: 'task-001',
        name: '锁门',
        description: '上锁大门门锁',
        status: 'completed',
        agentId: 'sh:security:001',
        agentName: 'SecurityAgent',
        startedAt: '2026-03-22T22:00:01.800Z',
        completedAt: '2026-03-22T22:00:02.400Z',
        result: '🔒 门锁已上锁',
        logs: [
          {
            id: 'log-004',
            timestamp: '2026-03-22T22:00:01.800Z',
            agentId: 'sh:security:001',
            agentName: 'SecurityAgent',
            role: 'sub',
            action: 'LockDoor',
            message: '大门门锁已上锁',
            duration: 600,
            status: 'success',
          },
        ],
      },
    ],
    logs: [
      {
        id: 'log-main-001',
        timestamp: '2026-03-22T22:00:00.100Z',
        agentId: 'sh:main:001',
        agentName: 'SmartHomeControlService',
        role: 'main',
        action: 'RouteToSceneMode',
        message: '识别到睡眠模式指令，开始多Agent联动',
        status: 'info',
      },
      {
        id: 'log-main-002',
        timestamp: '2026-03-22T22:00:02.500Z',
        agentId: 'sh:main:001',
        agentName: 'SmartHomeControlService',
        role: 'main',
        action: 'SceneModeComplete',
        message: '睡眠模式执行完成，4/4 子任务成功',
        duration: 2400,
        status: 'success',
      },
    ],
  },
  {
    id: 'task-002',
    name: '投诉处理',
    description: '用户情绪激动投诉订单问题，触发OrderAgent+TicketAgent协作+人工升级',
    status: 'completed',
    leaderAgentId: 'cs:leader-agent:001',
    leaderAgentName: 'CustomerServiceLeaderAgent',
    userInput: '太过分了！我的订单ORD-2024-001一直不发货，我要投诉！',
    createdAt: '2026-03-22T14:30:00Z',
    startedAt: '2026-03-22T14:30:00.050Z',
    completedAt: '2026-03-22T14:30:03.200Z',
    subTasks: [
      {
        id: 'sub-cs-001',
        parentTaskId: 'task-002',
        name: '查询订单',
        description: '获取订单ORD-2024-001详情',
        status: 'completed',
        agentId: 'cs:order:001',
        agentName: 'OrderAgent',
        startedAt: '2026-03-22T14:30:00.100Z',
        completedAt: '2026-03-22T14:30:00.800Z',
        result: '📦 订单ORD-2024-001 状态: shipped',
        logs: [
          {
            id: 'log-cs-001',
            timestamp: '2026-03-22T14:30:00.100Z',
            agentId: 'cs:order:001',
            agentName: 'OrderAgent',
            role: 'sub',
            action: 'QueryOrder',
            message: '查询订单 ORD-2024-001 详情',
            duration: 700,
            status: 'success',
          },
        ],
      },
      {
        id: 'sub-cs-002',
        parentTaskId: 'task-002',
        name: '创建紧急工单',
        description: '自动创建紧急投诉工单',
        status: 'completed',
        agentId: 'cs:ticket:001',
        agentName: 'TicketAgent',
        startedAt: '2026-03-22T14:30:01.000Z',
        completedAt: '2026-03-22T14:30:01.800Z',
        result: '📋 已创建紧急工单 TKT-URGENT-001',
        logs: [
          {
            id: 'log-cs-002',
            timestamp: '2026-03-22T14:30:01.000Z',
            agentId: 'cs:ticket:001',
            agentName: 'TicketAgent',
            role: 'sub',
            action: 'CreateTicket',
            message: '创建紧急工单，优先级: urgent，情绪升级: true',
            duration: 800,
            status: 'success',
            metadata: { priority: 'urgent', emotionEscalation: true },
          },
        ],
      },
      {
        id: 'sub-cs-003',
        parentTaskId: 'task-002',
        name: '人工客服升级',
        description: '升级到人工客服处理',
        status: 'completed',
        agentId: 'cs:escalation:001',
        agentName: 'EscalationService',
        startedAt: '2026-03-22T14:30:02.000Z',
        completedAt: '2026-03-22T14:30:03.100Z',
        result: '👤 已转接人工客服AGENT-VIP，预计等待1分钟',
        logs: [
          {
            id: 'log-cs-003',
            timestamp: '2026-03-22T14:30:02.000Z',
            agentId: 'cs:escalation:001',
            agentName: 'EscalationService',
            role: 'sub',
            action: 'EscalateToHuman',
            message: '投诉升级：用户情绪激动，优先级 urgent',
            duration: 1100,
            status: 'success',
            metadata: { agentId: 'AGENT-VIP', waitMinutes: 1 },
          },
        ],
      },
    ],
    logs: [
      {
        id: 'log-cs-main-001',
        timestamp: '2026-03-22T14:30:00.050Z',
        agentId: 'cs:leader-agent:001',
        agentName: 'CustomerServiceLeaderAgent',
        role: 'main',
        action: 'DetectEmotion',
        message: '检测到用户情绪: Angry，触发投诉协作流程',
        status: 'warning',
      },
      {
        id: 'log-cs-main-002',
        timestamp: '2026-03-22T14:30:03.200Z',
        agentId: 'cs:leader-agent:001',
        agentName: 'CustomerServiceLeaderAgent',
        role: 'main',
        action: 'ComplaintCoordinationComplete',
        message: '投诉协作完成：订单查询✓ 工单创建✓ 人工升级✓',
        duration: 3150,
        status: 'success',
      },
    ],
  },
];
